### ISSUE TITLE
Adding database causing FATAL EXCEPTION on Android 5

### ISSUE THREAD

**Issue by doneill** [couchbaselabs/couchbase-lite-tutorial-android#1]
Following your hello-world [tutorial](http://developer.couchbase.com/mobile/develop/training/build-first-android-app/create-manager-db/index.html) to the point in the code offered below results in the following exception:  

```
02-06 16:22:24.504  22557-22557/com.jdo.cb.hello_couchbase E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.jdo.cb.hello_couchbase, PID: 22557
    java.lang.NoSuchFieldError: no "I" field "mConnectionPtr" in class "Landroid/database/sqlite/SQLiteConnection;" or its superclasses
            at com.couchbase.touchdb.TDCollateJSON.nativeRegisterCustomCollators(Native Method)
            at com.couchbase.touchdb.TDCollateJSON.registerCustomCollators(TDCollateJSON.java:11)
            at com.couchbase.lite.android.AndroidSQLiteStorageEngine.open(AndroidSQLiteStorageEngine.java:46)
            at com.couchbase.lite.Database.open(Database.java:911)
            at com.couchbase.lite.Manager.getDatabase(Manager.java:227)
            at com.jdo.cb.hello_couchbase.MainActivity.onCreate(MainActivity.java:47)
            at android.app.Activity.performCreate(Activity.java:5933)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
02-06 16:25:10.842  23413-23413/com.jdo.cb.hello_couchbase E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.jdo.cb.hello_couchbase, PID: 23413
    java.lang.NoSuchFieldError: no "I" field "mConnectionPtr" in class "Landroid/database/sqlite/SQLiteConnection;" or its superclasses
            at com.couchbase.touchdb.TDCollateJSON.nativeRegisterCustomCollators(Native Method)
            at com.couchbase.touchdb.TDCollateJSON.registerCustomCollators(TDCollateJSON.java:11)
            at com.couchbase.lite.android.AndroidSQLiteStorageEngine.open(AndroidSQLiteStorageEngine.java:46)
            at com.couchbase.lite.Database.open(Database.java:911)
            at com.couchbase.lite.Manager.getDatabase(Manager.java:227)
            at com.jdo.cb.hello_couchbase.MainActivity.onCreate(MainActivity.java:47)
            at android.app.Activity.performCreate(Activity.java:5933)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

```

Offending code is line 47

```java
database = manager.getDatabase(dbname);

```

Full code so far

```java
final String TAG = "Hello-CouchBase";
Log.d(TAG, "Begin app");

// create a manager
Manager manager;
  try{
    manager = new Manager(new AndroidContext(this), Manager.DEFAULT_OPTIONS);
    Log.d(TAG, "Manager created");
  }catch (IOException e){
    Log.e(TAG, "Cannot create Manager object");
    return;
  }

  // create a name for the database and make sure the name is legal
  String dbname = "hello";
    if(!Manager.isValidDatabaseName(dbname)){
      Log.e(TAG, "Bad database name");
      return;
    }

    // create a new database
    Database database;
      try {
        database = manager.getDatabase(dbname);
        Log.d(TAG, "Database created");
      }catch (CouchbaseLiteException e){
        Log.e(TAG, "Cannot get database");
        return;
      }

Log.d(TAG, "End app");
```

**Comment by doneill** [comment]
I should add that the only diversion from your tutorial is that I am using ```minSdkVersion 15```.

**Comment by hideki** [comment]
Hi @doneill 

I assume you are using latest device that has latest CPU that couchbase lite 1.0.2 does not support.

At section of "Add Couchbase dependency", could you please try to use `compile 'com.couchbase.lite:couchbase-lite-android:1.0.4'` instead of `compile 'com.couchbase.lite:couchbase-lite-android:1.0.2'`

Please let us know if it works!

**Comment by doneill** [comment]
@hideki Yes, I am using Nexus 5 Android v 5.0.1 and using ```1.0.4``` worked!  Thanks for quick update/fix.

**Comment by hideki** [comment]
@doneill It is great to hear. We will update tutorial as soon as possible.
